In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.32930368,  0.97516242,  2.29987988],
       [ 0.02853411, -0.11576097, -1.26921698]])

In [3]:
data * 10

array([[  3.29303684,   9.75162421,  22.99879882],
       [  0.28534115,  -1.15760972, -12.69216984]])

In [4]:
data.shape

(2, 3)

- float16 - float256
- int8 - int256

In [5]:
data.dtype

dtype('float64')

In [6]:
data.ndim

2

In [7]:
a1 = np.empty((2, 3, 2))
a1


array([[[1.18830321e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.14587773e-312, 3.76231868e+174]],

       [[6.86912971e-091, 6.53029925e-042],
        [1.55092536e+184, 3.85527755e-057],
        [3.99910963e+252, 1.90979636e-312]]])

# asarray

In [14]:
b2 = np.asarray([1,2,3,4])
b2

array([1, 2, 3, 4])

In [9]:
b2[1][1] = 99

In [13]:
b2[1][1]

array([99., 99.])

In [12]:
b2

array([[[1.18830321e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.14587773e-312, 3.76231868e+174]],

       [[6.86912971e-091, 6.53029925e-042],
        [9.90000000e+001, 9.90000000e+001],
        [3.99910963e+252, 1.90979636e-312]]])

In [11]:
a1

array([[[1.18830321e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.14587773e-312, 3.76231868e+174]],

       [[6.86912971e-091, 6.53029925e-042],
        [9.90000000e+001, 9.90000000e+001],
        [3.99910963e+252, 1.90979636e-312]]])

In [15]:
c1 = a1.copy()
c1

array([[[1.18830321e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.14587773e-312, 3.76231868e+174]],

       [[6.86912971e-091, 6.53029925e-042],
        [9.90000000e+001, 9.90000000e+001],
        [3.99910963e+252, 1.90979636e-312]]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones_like(c1)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [19]:
np.full((5,2), 10)

array([10, 10, 10, 10, 10])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])