# numpy data types

In [2]:
import numpy as np

In [5]:
arr1 = np.array([1, 2, 3])
arr1, arr1.dtype

(array([1, 2, 3]), dtype('int32'))

In [6]:
arr1 = np.array([1, 2, 3], dtype="int16")
arr1, arr1.dtype

(array([1, 2, 3], dtype=int16), dtype('int16'))

In [27]:
arr1 = np.array([1,0], dtype="uint8")
arr1, arr1.dtype

(array([1, 0], dtype=uint8), dtype('uint8'))

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2


array([1, 2, 3])

In [31]:
arr2 = np.array([1, 2.2, 3])
arr2, arr2.dtype


(array([1. , 2.2, 3. ]), dtype('float64'))

## later on change the dtype

In [39]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [40]:
arr = arr.astype("float16")

In [41]:
arr.dtype

dtype('float16')

In [ ]:
int_array = np.arange(10)

# Arthmatic operations in ndarray

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr * arr[0]

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [44]:
arr * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [46]:
arr - 2

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [47]:
arr / 6

array([[0.16666667, 0.33333333, 0.5       ],
       [0.66666667, 0.83333333, 1.        ]])

In [52]:
arr ** 3

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

In [58]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [60]:
b = arr > arr2
b

array([[ True, False,  True],
       [False,  True, False]])

In [64]:
# doint with pythio list
for v1,v2 in zip(arr,arr2):
    print(v1>v2)
    

[ True False  True]
[False  True False]


In [61]:
b[0][0]

True

In [62]:
arr[1][1]

5.0

In [63]:
b[1][1]

True

In [65]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
arr >= 4 

array([[False, False, False],
       [ True,  True,  True]])

# basic indexing and slicing

In [79]:
arr = np.arange(10)
arr[5:8] = 12

arr_slice = arr[5:8]

arr,arr_slice

(array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9]), array([12, 12, 12]))

In [80]:
arr_slice[1] = 12345

In [81]:
arr_slice

array([   12, 12345,    12])

In [82]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [84]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d, arr2d.ndim, arr2d.dtype, arr2d.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 2,
 dtype('int32'),
 (3, 3))

In [85]:
arr2d[0]

array([1, 2, 3])

# boolean indexing

In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names.shape

(7,)

In [88]:
data = np.random.randn(7, 4)
data, data.shape


(array([[ 0.60502539, -0.34023513, -0.16628522, -1.64412212],
        [-0.68872914, -0.87779514,  0.02153281,  0.68035635],
        [-1.05634656, -0.3319679 , -1.11806016,  1.03805676],
        [-0.7553571 ,  0.84353907,  0.97828238,  0.53744063],
        [ 1.35952447, -0.7345102 ,  0.67790953,  0.49130387],
        [-0.38287862,  0.53617371,  0.89290678,  0.35960677],
        [-0.25018336, -0.18004465,  0.71724537, -0.04616509]]),
 (7, 4))

In [96]:
names == 'Joe'

array([False,  True, False, False, False,  True,  True])

In [111]:
(names == 'Bob') | (names == 'Joe')

array([ True,  True, False,  True, False,  True,  True])

In [107]:
(names == 'Joe')

array([False,  True, False, False, False,  True,  True])

In [115]:
data[(names == 'Bob') | (names == 'Joe'), 2:]

array([[-0.16628522, -1.64412212],
       [ 0.02153281,  0.68035635],
       [ 0.97828238,  0.53744063],
       [ 0.89290678,  0.35960677],
       [ 0.71724537, -0.04616509]])

In [116]:
data[(names != 'Bob') ]

array([[-0.68872914, -0.87779514,  0.02153281,  0.68035635],
       [-1.05634656, -0.3319679 , -1.11806016,  1.03805676],
       [ 1.35952447, -0.7345102 ,  0.67790953,  0.49130387],
       [-0.38287862,  0.53617371,  0.89290678,  0.35960677],
       [-0.25018336, -0.18004465,  0.71724537, -0.04616509]])

In [117]:
data

array([[ 0.60502539, -0.34023513, -0.16628522, -1.64412212],
       [-0.68872914, -0.87779514,  0.02153281,  0.68035635],
       [-1.05634656, -0.3319679 , -1.11806016,  1.03805676],
       [-0.7553571 ,  0.84353907,  0.97828238,  0.53744063],
       [ 1.35952447, -0.7345102 ,  0.67790953,  0.49130387],
       [-0.38287862,  0.53617371,  0.89290678,  0.35960677],
       [-0.25018336, -0.18004465,  0.71724537, -0.04616509]])

In [120]:
data[data < 0] = 0

In [121]:
data

array([[0.60502539, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02153281, 0.68035635],
       [0.        , 0.        , 0.        , 1.03805676],
       [0.        , 0.84353907, 0.97828238, 0.53744063],
       [1.35952447, 0.        , 0.67790953, 0.49130387],
       [0.        , 0.53617371, 0.89290678, 0.35960677],
       [0.        , 0.        , 0.71724537, 0.        ]])

# Fancy indexing

In [122]:
arr = np.empty((8, 4))
arr

array([[1.56832564e-311, 1.03753786e-321, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 3.22115944e-057,
        1.67534158e-076],
       [4.04554448e-037, 1.95375109e+184, 1.13774569e-042,
        2.16385130e+190],
       [1.94918964e-153, 4.90838520e+252, 1.30304358e-142,
        1.06396443e+224],
       [1.70100503e+256, 5.49109388e-143, 9.30537467e+199,
        5.91664635e-038],
       [1.56129606e+184, 2.21419765e-052, 3.59959088e+175,
        4.40497146e-143],
       [5.49810101e-143, 5.88969958e-091, 7.77053662e-043,
        2.40463294e-057],
       [4.29600460e-096, 4.82337433e+228, 3.67152456e-062,
        1.58268989e-319]])

In [123]:
for i in range(8):
    arr[i] = i

In [124]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

4306

In [130]:
arr[4][1]

4.0

In [133]:
arr[[6,5,4]]

array([[6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [4., 4., 4., 4.]])

In [136]:
arr[[4,3,0,6],[3,1,2,0]]

array([4., 3., 0., 6.])

In [137]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [139]:
arr[[1, 5, 7, 2]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [141]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [143]:
arr[[4,3,0,6]]  [:,[3,1,2,0]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

In [146]:
a = arr[[4,3,0,6]] 

a[:,[3,1,2,0]]

array([[19, 17, 18, 16],
       [15, 13, 14, 12],
       [ 3,  1,  2,  0],
       [27, 25, 26, 24]])